"""fix: add VARCHAR lengths

Revision ID: 08dbf440e109
Revises: 81857efdd2a8
Create Date: 2025-07-18 11:35:37.697711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '08dbf440e109'
down_revision: Union[str, Sequence[str], None] = '81857efdd2a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_table('visa_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('visa_format', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('requirements', sa.String(length=1000), nullable=True),
    sa.Column('processing_time', sa.String(length=100), nullable=True),
    sa.Column('service_fee', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visa_types_id'), 'visa_types', ['id'], unique=False)
    op.create_index(op.f('ix_destination_images_destination_id'), 'destination_images', ['destination_id'], unique=False)
    op.add_column('destinations', sa.Column('region_id', sa.Integer(), nullable=True))
    op.alter_column('destinations', 'description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_destinations_region_id'), 'destinations', ['region_id'], unique=False)
    op.create_foreign_key(None, 'destinations', 'regions', ['region_id'], ['id'])
    op.drop_column('destinations', 'region')
    op.add_column('leads', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('leads', 'full_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('leads', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('leads', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_source'), 'leads', ['source'], unique=False)
    op.create_index(op.f('ix_package_images_package_id'), 'package_images', ['package_id'], unique=False)
    op.alter_column('packages', 'slug',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('packages', 'rating',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               type_=sa.DECIMAL(precision=3, scale=1),
               existing_nullable=True)
    op.drop_index(op.f('slug'), table_name='packages')
    op.create_index(op.f('ix_packages_category_id'), 'packages', ['category_id'], unique=False)
    op.create_index(op.f('ix_packages_destination_id'), 'packages', ['destination_id'], unique=False)
    op.create_index(op.f('ix_packages_slug'), 'packages', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packages_slug'), table_name='packages')
    op.drop_index(op.f('ix_packages_destination_id'), table_name='packages')
    op.drop_index(op.f('ix_packages_category_id'), table_name='packages')
    op.create_index(op.f('slug'), 'packages', ['slug'], unique=True)
    op.alter_column('packages', 'rating',
               existing_type=sa.DECIMAL(precision=3, scale=1),
               type_=mysql.DECIMAL(precision=2, scale=1),
               existing_nullable=True)
    op.alter_column('packages', 'slug',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_package_images_package_id'), table_name='package_images')
    op.drop_index(op.f('ix_leads_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.alter_column('leads', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('leads', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('leads', 'full_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('leads', 'updated_at')
    op.add_column('destinations', sa.Column('region', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'destinations', type_='foreignkey')
    op.drop_index(op.f('ix_destinations_region_id'), table_name='destinations')
    op.alter_column('destinations', 'description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('destinations', 'region_id')
    op.drop_index(op.f('ix_destination_images_destination_id'), table_name='destination_images')
    op.drop_index(op.f('ix_visa_types_id'), table_name='visa_types')
    op.drop_table('visa_types')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
